version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript-development:
        dependency-type: development
      javascript-production:
        dependency-type: production

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /engines/drawscope-engine
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

